name: ca_place_holder
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  freezed_annotation: ^2.0.3
  http: ^0.13.4
  data_connection_checker_tv: ^0.3.5-nullsafety
  get_it: ^7.2.0
  mockito: ^5.2.0
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  lint: ^1.8.2

flutter:

  uses-material-design: true